#!/usr/bin/env python3
"""
build.py
========
Packages both programs with PyInstaller into one folder
(signature: By RumpleSteelSkin):

  dist/BlerpDownloader/
    ├── BlerpDownloader.exe   — GUI (windowed, no console)
    ├── blerp.exe             — Console (command line)
    └── ...                     shared Python runtime and DLLs

A folder build, not one-file: see write_spec() for why. The two executables
share a single copy of the runtime rather than carrying one each.

Embeds the icon (assets/icon.ico) both as the exe icon and inside the bundle
for the window icon. Signature info (CompanyName/LegalCopyright) is also
written to the exe's "Properties > Details" tab (version_info.txt).

Usage:  python build.py        (installs PyInstaller automatically if missing)

Note: ffmpeg/ffprobe are NOT bundled; they must be on PATH on the machine
that runs it.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import blerp_downloader as core

# The Windows console (cp1252) doesn't have the ✓ printed below when stdout
# isn't a real console (e.g. piped); reconfigure to UTF-8 so it doesn't crash.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parent
ICON = ROOT / "assets" / "icon.ico"
VERSION_FILE = ROOT / "version_info.txt"
SPEC_FILE = ROOT / "BlerpDownloader.spec"
APP_DIR = "BlerpDownloader"   # dist/<APP_DIR>/ holds both executables

AUTHOR = core.__author__
VERSION = core.__version__
_vtuple = ", ".join((VERSION.split(".") + ["0", "0", "0", "0"])[:4])


def ensure_pyinstaller() -> None:
    try:
        import PyInstaller  # noqa: F401
    except ImportError:
        print("Installing PyInstaller...")
        subprocess.run([sys.executable, "-m", "pip", "install", "pyinstaller"], check=True)


def write_version_info() -> None:
    """Writes the version/signature resource shown in the exe's 'Properties' dialog."""
    VERSION_FILE.write_text(f"""# UTF-8
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({_vtuple}), prodvers=({_vtuple}),
    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)
  ),
  kids=[
    StringFileInfo([StringTable('040904B0', [
      StringStruct('CompanyName', '{AUTHOR}'),
      StringStruct('FileDescription', 'Blerp Downloader'),
      StringStruct('FileVersion', '{VERSION}'),
      StringStruct('InternalName', 'BlerpDownloader'),
      StringStruct('LegalCopyright', 'By {AUTHOR}'),
      StringStruct('OriginalFilename', 'BlerpDownloader.exe'),
      StringStruct('ProductName', 'Blerp Downloader'),
      StringStruct('ProductVersion', '{VERSION}'),
    ])]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
""", encoding="utf-8")


def pyinstaller(*args: str) -> None:
    subprocess.run([sys.executable, "-m", "PyInstaller", *args], check=True, cwd=ROOT)


def write_spec() -> Path:
    """Generates the PyInstaller spec that puts both executables in one folder.

    A folder build rather than one-file: a one-file exe unpacks its whole
    runtime into %TEMP% on every launch, and if anything disturbs that - an
    antivirus scanning a freshly written unsigned exe, temp cleanup - the app
    dies with "Failed to load Python DLL". A folder build has nothing to unpack,
    so it starts faster and that failure cannot happen. Since the app ships as an
    installer anyway, one-file bought us nothing.

    Both programs go through a single COLLECT so they share one copy of Python
    and the DLLs instead of carrying a set each.
    """
    def analysis(script: str) -> str:
        return (f"Analysis([r'{script}'], pathex=[r'{ROOT}'], binaries=[],\n"
                f"         datas=[(r'{ICON}', 'assets')], hiddenimports=[],\n"
                f"         hookspath=[], hooksconfig={{}}, runtime_hooks=[],\n"
                f"         excludes=[], noarchive=False, optimize=0)")

    spec = SPEC_FILE
    spec.write_text(f"""# -*- mode: python ; coding: utf-8 -*-
# Generated by build.py - edit that, not this.

gui_a = {analysis('blerp_gui.py')}
cli_a = {analysis('blerp_to_mp4.py')}

gui_pyz = PYZ(gui_a.pure)
cli_pyz = PYZ(cli_a.pure)

gui_exe = EXE(gui_pyz, gui_a.scripts, [], exclude_binaries=True,
              name='BlerpDownloader', debug=False, bootloader_ignore_signals=False,
              strip=False, upx=True, console=False, disable_windowed_traceback=False,
              argv_emulation=False, target_arch=None, codesign_identity=None,
              entitlements_file=None, icon=[r'{ICON}'], version=r'{VERSION_FILE}')

cli_exe = EXE(cli_pyz, cli_a.scripts, [], exclude_binaries=True,
              name='blerp', debug=False, bootloader_ignore_signals=False,
              strip=False, upx=True, console=True, disable_windowed_traceback=False,
              argv_emulation=False, target_arch=None, codesign_identity=None,
              entitlements_file=None, icon=[r'{ICON}'], version=r'{VERSION_FILE}')

COLLECT(gui_exe, gui_a.binaries, gui_a.datas,
        cli_exe, cli_a.binaries, cli_a.datas,
        strip=False, upx=True, upx_exclude=[], name='{APP_DIR}')
""", encoding="utf-8")
    return spec


def main() -> None:
    if not ICON.exists():
        print("No icon found; run `python generate_logo.py` first.")
        sys.exit(1)
    ensure_pyinstaller()
    write_version_info()

    print(f"\n=== Packaging {APP_DIR}/ (BlerpDownloader.exe + blerp.exe) ===")
    pyinstaller("--noconfirm", "--clean", str(write_spec()))

    # installer.iss reads this so the version lives in exactly one place
    # (blerp_downloader/__init__.py) instead of being duplicated in the .iss.
    (ROOT / "dist" / "VERSION.txt").write_text(VERSION, encoding="ascii")

    out = ROOT / "dist" / APP_DIR
    print(f"\n✓ Done.  {out}\\  contains BlerpDownloader.exe + blerp.exe"
          f"   ·  By {AUTHOR}")


if __name__ == "__main__":
    main()
